:global:
  build:
    matrix:
      - GOOS: linux
        GOARCH: amd64
.travis.yml:
  sudo: true
  deploy:
    access_key_id: AKIAINMB43VSSPFZISAA
    secret_access_key:
      secure: x/44U2ADuqQsBLzO/E0Uae3yD2vWevsucpZEERPynMZ0XJ18VTHK11VyTPJUkk9rBVASwCR1+FR0vAQWQnQZH5Wxd6GCBgx3NDGW0HCsTsESE4LGZ9Zb5CwSRIVrR9PJQ5mtohkDCHG+1jBVrnOJg/mB7SuSvPKIj5TrvjACEWmJaUSfkqRrl/V5NwccQiHUn0zeQAkzVZklpCprOs80KkZMOVdRJ2AD8Q2w61DSFiucGXkQct6AMTtIejuWVkZd8X3EnZ8kx8Rwd1omeN+z6AdYM5B3aDxSmX00xaUnzzFcYzqGTHhrobbaVZL684eXUy7AkLMHyUkEvWlZ7A1TElL92Yzbrj4nyzu64PkcwlwwwdnLVoK8XkGx8y2021k7oK3phrXGkYdJ0rBR26U5/6v/MYJ4MQMMWgTdhs0nvexXREUTURVP14aHYxjxh4lAD/4PQwwRqSh32gnkrvNg/TZwuYeCqZV1SdmMOzHAtcpUL1bfmkg7i5xD31aTdnqvbeRqHF7aIDiIk1UugfPXBtg49TDfVXBELypm6/mUU1ggdpb4r943DMjq6jlcVZyUi4KXhFCRWdb+0QGKSJYpJ1SO6FmHc0sMWSsUjlu7OmOPdc0HwK0aHC4GChoT8T6ad11N+LhnesA5VklQhZJ0pOhuTWHM4AKI8JoplfPYALw=
    api_key:
      secure: BeCvsiKMuuLGeEI13m0gTZuGwpER9RRbQlkPsH/kpAmtoVhQnZU8nSktSH7JTnUx/lHIyuCOFlHXIerZA/rHk7xPy8VXBOIrjNcEnEvnlPkeqUwgRsC9C8gqlrD8i9mRxo7+NK+HE8JXjSHFdmAnlnD7kkjFfnSAL4fwT0j4HGGGWIYGJyk3b3jToPZwlHoLfCWwHYGvS9c/jvz7lMt9u2nWP7cxvnFIV8qB069HG0PTgPRsHIMuxkVKPRoGw0YPKeKgHfRwiMkUYFh8ewnK+ypzslxbYolnYOn6B6rQ+g4WF8EDFhBJDuhZekzPckKN7eeTgHzzNSsKQi07tn/1NEtS+MfMqyVcrZ931wMJWf37tsK3cGkGeKG69xW3N4wioYeXqGFv4iy9caaM0r+tyqVtdZ2Gn8KKM7d8S5nNiUzfa/qtoiou4u/O/2JGBgvasimkjgdXBcupyJ6kBjZ9GIODoZ12RVp8NiUNLSpmCZd5x58JyWJlO4hm7xdmMXc4kgcqV8Wzuy6uwfy45orenZBjiPqskeQzPERU0qy+9UZm6IGcY3OQ+lDRR4liu2VtkPvafttKbHtEuzwXOlHDC+gj2vs/pJLsnjxuK8LYeGQVZ9PMQzIQL5lie70WhgTL9jU4igk4LSATeIWaYCvL0Z4cfNj8lIgvTJkIrXu+0po=
 
