# File managed by pluginsync
sudo: true
language: go
go:
- 1.6.x
- 1.7.x
env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  - GLIDE_HOME="${HOME}/.glide"
  matrix:
  - TEST_TYPE=small
  - TEST_TYPE=build
matrix:
  exclude:
  - go: 1.6.x
    env: TEST_TYPE=build
before_install:
- "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"
install:
- cd $SNAP_PLUGIN_SOURCE
- make deps
script:
- make check 2>&1
notifications:
  email: false
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
before_deploy:
- "./scripts/pre_deploy.sh"
deploy:
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: MZWqb0f0IAWTAP/WxEEjugGQUn6oy8AKZRO3ui49EoCBlAJdy9bqBkuRU51abH2b5DysLDg0pdftY0AbE60vwdood5cTdtnVhOtxIjqs2YetRWUgQHvZ0OFCoaHUvdTf3r34VexXIqI7tiHXnzJTmCw91milzUtmnizOsgR0GA5TwxoBPeUT5u2jz2JxsJ0OUL3ijzRnRamMj7D6prU8f9ulkFLhN6eSKjiorZOwHx9Rt/su1uSDwHxSWpzJ7l/s0RbDxsQIzjzaVabSEQVmVgs4EZejuXb/y2xeUsalRE5IB/scagez4786u2j2lbHuyiLMV5LUCcTVgnB3qzXywRHA1dNBL2BkSfcv2i0uvtFEG52h6oa+FtYuIm3dq+3/6WaaGIcaEJCimQJc+R0ZiNufTHNwXoker5IdsDovUIqHdmf/0frC6Vvp66AbQruCyRC16SUOKjgMFpLSIUyzqlXk6BAhNtCOae/VWQGuhS5xzzhsKcjRoHSd8aBXqowhKjlzFcVnITKdp/edyal+335R4HzH5VDhFUcdIVyEufT4N7NvpNSFhWzrvrLfy6HfI9yNUYuZUWB74MJ8xGRk4JtoWaOXmhG4ZI/0yPR6g6Tpq7CwnCqcJyU4IqNMPIQhB5X+fDDxE6gpTMRv35v/6pFyhLW0fGOBKoV4ahkAQcI=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-collector-logs
    branch: master
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION =~ ^1\.7\.[0-9]+$
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: MZWqb0f0IAWTAP/WxEEjugGQUn6oy8AKZRO3ui49EoCBlAJdy9bqBkuRU51abH2b5DysLDg0pdftY0AbE60vwdood5cTdtnVhOtxIjqs2YetRWUgQHvZ0OFCoaHUvdTf3r34VexXIqI7tiHXnzJTmCw91milzUtmnizOsgR0GA5TwxoBPeUT5u2jz2JxsJ0OUL3ijzRnRamMj7D6prU8f9ulkFLhN6eSKjiorZOwHx9Rt/su1uSDwHxSWpzJ7l/s0RbDxsQIzjzaVabSEQVmVgs4EZejuXb/y2xeUsalRE5IB/scagez4786u2j2lbHuyiLMV5LUCcTVgnB3qzXywRHA1dNBL2BkSfcv2i0uvtFEG52h6oa+FtYuIm3dq+3/6WaaGIcaEJCimQJc+R0ZiNufTHNwXoker5IdsDovUIqHdmf/0frC6Vvp66AbQruCyRC16SUOKjgMFpLSIUyzqlXk6BAhNtCOae/VWQGuhS5xzzhsKcjRoHSd8aBXqowhKjlzFcVnITKdp/edyal+335R4HzH5VDhFUcdIVyEufT4N7NvpNSFhWzrvrLfy6HfI9yNUYuZUWB74MJ8xGRk4JtoWaOXmhG4ZI/0yPR6g6Tpq7CwnCqcJyU4IqNMPIQhB5X+fDDxE6gpTMRv35v/6pFyhLW0fGOBKoV4ahkAQcI=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-collector-logs
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION =~ ^1\.7\.[0-9]+$
- provider: releases
  api_key:
    secure: EDcIkAGQ/T55uh4OLLcp6mk2QZHIEZomiRZKjnup3PQXtqioiC6xqsILwe5DduzeBmf8vZV29OUUfj2BnR29wU9sxLRBTgcoj80kSPlTEQYTbCqFEhEnmuy5QhW+rynVTFp+eari9LuYQ3G/1sA6ktmfYoyux3tkw/fKdzL4DkBr82Ix1QJeLzXJMHkZN7MvPIlYdw8wWbpB2xd482k00jq4EdieBSx/W08lE3m6CAWsjdD7HB0SwNf6DiPaz/FhmIVg+YkGajFb9f4Q2P97vmSHy3577II8NAX3w7MWwYIRkq2Kgl8ZmUfIUtxeMoIfAu8DPqhKKztkEz/1WwvR8RamDaNQCIOcKQVI5ciGzrLxI6Om+0OIf+MPMOo2gT7OYwtJ+jwVnBbtrAin9GiQvSYVjEApiQiTDIodp4uyI6nwUFhtidq8kBLnZWik6xif763WDQDSYfMpk2VjPBqinf7pCVf3OUSMoJCLJlPRslaU6SejwuXcpi9sZ3+8hwkOCcYLz2jFty8gnJa4gFsvRP/jdYMo4VHBCPInaZNOTV3Gtnvc45S4+/Z/VOke/H78poF27YAezdio/0bSxa+8AHPwg/3pibxokPgFtV6bWp2GSWg3yA5QISr7GY2GeVdOKT0oR4KoQHeoetPkzoVYIZHrFkTBA44Rj68AXOAtNkA=
  file:
    - release/snap-plugin-collector-logs_linux_x86_64
  skip_cleanup: true
  on:
    repo: intelsdi-x/snap-plugin-collector-logs
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION =~ ^1\.7\.[0-9]+$
